import { AftershipResponse } from '../model/aftership_response';
import { Notification } from '../model/notification/notification';
import { NotificationRequest } from '../model/notification/notification_request';
/**
 * Get, add or remove contacts (sms or email) to be notified when the status of a tracking has changed.
 */
export interface NotificationEndpoint {
  /**
   * Get contact information for the users to notify when the tracking changes.
   * Please note that only customer receivers will be returned.
   * Any email, sms or webhook that belongs to the Store will not be returned.
   * Either one tracking_id or (slug + tracking_number) should be specified.
   * @param tracking_id A unique identifier generated by AfterShip for the tracking.
   * @param slug Unique code of courier
   * @param tracking_number Tracking number of a shipment.
   */
  getNotification(
    tracking_id?: string,
    slug?: string,
    tracking_number?: string,
  ): Promise<AftershipResponse<Notification>>;

  /**
   * Add notification receivers to a tracking id (number).
   * Either one tracking_id or (slug + tracking_number) should be specified.
   * @param notification Notification Request Object
   * @param tracking_id A unique identifier generated by AfterShip for the tracking.
   * @param slug Unique code of courier
   * @param tracking_number Tracking number of a shipment.
   */
  addNotification(
    notification: NotificationRequest,
    tracking_id?: string,
    slug?: string,
    tracking_number?: string,
  ): Promise<AftershipResponse<Notification>>;

  /**
   * Remove notification receivers from a tracking id (number).
   * Either one tracking_id or (slug + tracking_number) should be specified.
   * @param notification Notification Request Object
   * @param tracking_id A unique identifier generated by AfterShip for the tracking.
   * @param slug Unique code of courier
   * @param tracking_number Tracking number of a shipment.
   */
  removeNotification(
    notification: NotificationRequest,
    tracking_id?: string,
    slug?: string,
    tracking_number?: string,
  ): Promise<AftershipResponse<Notification>>;
}
