/**
 * The param to identify the single tracking.
 * Either tracking_id or (slug + tracking_number) should be specified.
 */
export interface SingleTrackingParam {
  /**
   * A unique identifier generated by AfterShip for the tracking.
   */
  tracking_id?: string;

  /**
   * Unique code of courier
   */
  slug?: string;

  /**
   * Tracking number of a shipment.
   */
  tracking_number?: string;
}
