/**
 * Tracking Object
 */
export interface Tracking {
  /**
   * A unique identifier generated by AfterShip for the tracking.
   */
  id: string;

  /**
   * Tracking number.
   */
  tracking_number: string;

  /**
   * The postal code of receiver's address. Required by some couriers, such asdeutsch-post
   */
  tracking_postal_code: string;

  /**
   * Shipping date in YYYYMMDD format. Required by some couriers, such asdeutsch-post
   */
  tracking_ship_date: string;

  /**
   * Key of the shipment for a specific courier. Required by some couriers, such assic-teliway
   */
  tracking_key: string;

  /**
   * Origin Country of the shipment for a specific courier. Required by some couriers, such asdhl
   */
  tracking_origin_country: string;

  /**
   * Destination Country of the shipment for a specific courier. Required by some couriers, such aspostnl-3s
   */
  tracking_destination_country: string;

  /**
   * Located state of the shipment for a specific courier. Required by some couriers, such asstar-track-courier
   */
  tracking_state: string;

  /**
   * Account number of the shipper for a specific courier. Required by some couriers, such asdynamic-logistics
   */
  tracking_account_number: string;

  /**
   * Unique code of courier. Get courier slug here https://docs.aftership.com/api/4/couriers
   */
  slug: string;
}
